# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConvoluteKernelDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConvoluteKernelDialog(object):
    def setupUi(self, ConvoluteKernelDialog):
        ConvoluteKernelDialog.setObjectName("ConvoluteKernelDialog")
        ConvoluteKernelDialog.resize(279, 275)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConvoluteKernelDialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 210, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.kernelValueSpinBox1x1 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox1x1.setGeometry(QtCore.QRect(30, 120, 42, 22))
        self.kernelValueSpinBox1x1.setMinimum(-100)
        self.kernelValueSpinBox1x1.setMaximum(100)
        self.kernelValueSpinBox1x1.setObjectName("kernelValueSpinBox1x1")
        self.label = QtWidgets.QLabel(ConvoluteKernelDialog)
        self.label.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ConvoluteKernelDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(ConvoluteKernelDialog)
        self.comboBox.setGeometry(QtCore.QRect(100, 30, 141, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(ConvoluteKernelDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 231, 16))
        self.label_3.setObjectName("label_3")
        self.kernelValueSpinBox1x2 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox1x2.setGeometry(QtCore.QRect(80, 120, 42, 22))
        self.kernelValueSpinBox1x2.setMinimum(-100)
        self.kernelValueSpinBox1x2.setMaximum(100)
        self.kernelValueSpinBox1x2.setObjectName("kernelValueSpinBox1x2")
        self.kernelValueSpinBox1x3 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox1x3.setGeometry(QtCore.QRect(130, 120, 42, 22))
        self.kernelValueSpinBox1x3.setMinimum(-100)
        self.kernelValueSpinBox1x3.setMaximum(100)
        self.kernelValueSpinBox1x3.setObjectName("kernelValueSpinBox1x3")
        self.kernelValueSpinBox2x1 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox2x1.setGeometry(QtCore.QRect(30, 150, 42, 22))
        self.kernelValueSpinBox2x1.setMinimum(-100)
        self.kernelValueSpinBox2x1.setMaximum(100)
        self.kernelValueSpinBox2x1.setObjectName("kernelValueSpinBox2x1")
        self.kernelValueSpinBox2x2 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox2x2.setGeometry(QtCore.QRect(80, 150, 42, 22))
        self.kernelValueSpinBox2x2.setMinimum(-100)
        self.kernelValueSpinBox2x2.setMaximum(100)
        self.kernelValueSpinBox2x2.setObjectName("kernelValueSpinBox2x2")
        self.kernelValueSpinBox2x3 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox2x3.setGeometry(QtCore.QRect(130, 150, 42, 22))
        self.kernelValueSpinBox2x3.setMinimum(-100)
        self.kernelValueSpinBox2x3.setMaximum(100)
        self.kernelValueSpinBox2x3.setObjectName("kernelValueSpinBox2x3")
        self.kernelValueSpinBox3x1 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox3x1.setGeometry(QtCore.QRect(30, 180, 42, 22))
        self.kernelValueSpinBox3x1.setMinimum(-100)
        self.kernelValueSpinBox3x1.setMaximum(100)
        self.kernelValueSpinBox3x1.setObjectName("kernelValueSpinBox3x1")
        self.kernelValueSpinBox3x2 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox3x2.setGeometry(QtCore.QRect(80, 180, 42, 22))
        self.kernelValueSpinBox3x2.setMinimum(-100)
        self.kernelValueSpinBox3x2.setMaximum(100)
        self.kernelValueSpinBox3x2.setObjectName("kernelValueSpinBox3x2")
        self.kernelValueSpinBox3x3 = QtWidgets.QSpinBox(ConvoluteKernelDialog)
        self.kernelValueSpinBox3x3.setGeometry(QtCore.QRect(130, 180, 42, 22))
        self.kernelValueSpinBox3x3.setMinimum(-100)
        self.kernelValueSpinBox3x3.setMaximum(100)
        self.kernelValueSpinBox3x3.setObjectName("kernelValueSpinBox3x3")

        self.retranslateUi(ConvoluteKernelDialog)
        self.buttonBox.accepted.connect(ConvoluteKernelDialog.accept)
        self.buttonBox.rejected.connect(ConvoluteKernelDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConvoluteKernelDialog)

    def retranslateUi(self, ConvoluteKernelDialog):
        _translate = QtCore.QCoreApplication.translate
        ConvoluteKernelDialog.setWindowTitle(_translate("ConvoluteKernelDialog", "Dialog"))
        self.label.setText(_translate("ConvoluteKernelDialog", "Kernel Values"))
        self.label_2.setText(_translate("ConvoluteKernelDialog", "Default Kernel"))
        self.comboBox.setItemText(0, _translate("ConvoluteKernelDialog", "Blur"))
        self.comboBox.setItemText(1, _translate("ConvoluteKernelDialog", "Prewitt"))
        self.comboBox.setItemText(2, _translate("ConvoluteKernelDialog", "SobelX"))
        self.comboBox.setItemText(3, _translate("ConvoluteKernelDialog", "SobelY"))
        self.comboBox.setItemText(4, _translate("ConvoluteKernelDialog", "Laplace"))
        self.comboBox.setItemText(5, _translate("ConvoluteKernelDialog", "Sharpen"))
        self.label_3.setText(_translate("ConvoluteKernelDialog", "WARNING: Will replace inputted kernel values"))
