# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomConvKernelDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomConvKernelDialog(object):
    def setupUi(self, CustomConvKernelDialog):
        CustomConvKernelDialog.setObjectName("CustomConvKernelDialog")
        CustomConvKernelDialog.resize(400, 287)
        self.buttonBox = QtWidgets.QDialogButtonBox(CustomConvKernelDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(CustomConvKernelDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(25)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit)
        self.label_3 = QtWidgets.QLabel(CustomConvKernelDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 361, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(CustomConvKernelDialog)
        self.buttonBox.accepted.connect(CustomConvKernelDialog.accept)
        self.buttonBox.rejected.connect(CustomConvKernelDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CustomConvKernelDialog)

    def retranslateUi(self, CustomConvKernelDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomConvKernelDialog.setWindowTitle(_translate("CustomConvKernelDialog", "Custom convolution kernel settings"))
        self.label.setText(_translate("CustomConvKernelDialog", "Kernel Size(VALxVAL)"))
        self.label_2.setText(_translate("CustomConvKernelDialog", "Values"))
        self.label_3.setText(_translate("CustomConvKernelDialog", "WARNING: Values has to be separated by space and be integers"))
