# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GrayScaleDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_grayScaleDialog(object):
    def setupUi(self, grayScaleDialog):
        grayScaleDialog.setObjectName("grayScaleDialog")
        grayScaleDialog.resize(400, 119)
        grayScaleDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(grayScaleDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 60, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(grayScaleDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)

        self.retranslateUi(grayScaleDialog)
        self.buttonBox.accepted.connect(grayScaleDialog.accept)
        self.buttonBox.rejected.connect(grayScaleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(grayScaleDialog)

    def retranslateUi(self, grayScaleDialog):
        _translate = QtCore.QCoreApplication.translate
        grayScaleDialog.setWindowTitle(_translate("grayScaleDialog", "Grayscale settings"))
        self.label.setText(_translate("grayScaleDialog", "Color Channel"))
        self.comboBox.setItemText(0, _translate("grayScaleDialog", "Red"))
        self.comboBox.setItemText(1, _translate("grayScaleDialog", "Green"))
        self.comboBox.setItemText(2, _translate("grayScaleDialog", "Blue"))
