# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JpegCompressionQualtyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JpegCompressionQualityDialog(object):
    def setupUi(self, JpegCompressionQualityDialog):
        JpegCompressionQualityDialog.setObjectName("JpegCompressionQualityDialog")
        JpegCompressionQualityDialog.resize(399, 169)
        self.buttonBox = QtWidgets.QDialogButtonBox(JpegCompressionQualityDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 110, 351, 32))
        self.buttonBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(JpegCompressionQualityDialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(JpegCompressionQualityDialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 50, 351, 22))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(JpegCompressionQualityDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(JpegCompressionQualityDialog)
        self.label_3.setGeometry(QtCore.QRect(180, 80, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(JpegCompressionQualityDialog)
        self.label_4.setGeometry(QtCore.QRect(360, 80, 41, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(JpegCompressionQualityDialog)
        self.buttonBox.accepted.connect(JpegCompressionQualityDialog.accept)
        self.buttonBox.rejected.connect(JpegCompressionQualityDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(JpegCompressionQualityDialog)

    def retranslateUi(self, JpegCompressionQualityDialog):
        _translate = QtCore.QCoreApplication.translate
        JpegCompressionQualityDialog.setWindowTitle(_translate("JpegCompressionQualityDialog", "JPEG Compression Quality"))
        self.label.setText(_translate("JpegCompressionQualityDialog", "Compression Quality"))
        self.label_2.setText(_translate("JpegCompressionQualityDialog", "Worst"))
        self.label_3.setText(_translate("JpegCompressionQualityDialog", "Medium"))
        self.label_4.setText(_translate("JpegCompressionQualityDialog", "Best"))
