# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphOpsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MorphOpsDialog(object):
    def setupUi(self, MorphOpsDialog):
        MorphOpsDialog.setObjectName("MorphOpsDialog")
        MorphOpsDialog.resize(389, 232)
        self.buttonBox = QtWidgets.QDialogButtonBox(MorphOpsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 190, 341, 32))
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(MorphOpsDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(MorphOpsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 351, 153))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dilationRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.dilationRadioButton.setChecked(True)
        self.dilationRadioButton.setObjectName("dilationRadioButton")
        self.verticalLayout.addWidget(self.dilationRadioButton)
        self.erosionRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.erosionRadioButton.setObjectName("erosionRadioButton")
        self.verticalLayout.addWidget(self.erosionRadioButton)
        self.openingRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.openingRadioButton.setObjectName("openingRadioButton")
        self.verticalLayout.addWidget(self.openingRadioButton)
        self.closingRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.closingRadioButton.setObjectName("closingRadioButton")
        self.verticalLayout.addWidget(self.closingRadioButton)
        self.thinningRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.thinningRadioButton.setObjectName("thinningRadioButton")
        self.verticalLayout.addWidget(self.thinningRadioButton)
        self.thickeningRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.thickeningRadioButton.setObjectName("thickeningRadioButton")
        self.verticalLayout.addWidget(self.thickeningRadioButton)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(MorphOpsDialog)
        self.buttonBox.accepted.connect(MorphOpsDialog.accept)
        self.buttonBox.rejected.connect(MorphOpsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MorphOpsDialog)

    def retranslateUi(self, MorphOpsDialog):
        _translate = QtCore.QCoreApplication.translate
        MorphOpsDialog.setWindowTitle(_translate("MorphOpsDialog", "Morphological Operations Settings"))
        self.label_2.setText(_translate("MorphOpsDialog", "Type:"))
        self.dilationRadioButton.setText(_translate("MorphOpsDialog", "Dilation"))
        self.erosionRadioButton.setText(_translate("MorphOpsDialog", "Erosion"))
        self.openingRadioButton.setText(_translate("MorphOpsDialog", "Opening"))
        self.closingRadioButton.setText(_translate("MorphOpsDialog", "Closing"))
        self.thinningRadioButton.setText(_translate("MorphOpsDialog", "Hit-Or-Miss Thinning"))
        self.thickeningRadioButton.setText(_translate("MorphOpsDialog", "Hit-Or-Miss Thickening"))
        self.label.setText(_translate("MorphOpsDialog", "WARNING: This will binarize the image"))
