# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreAnalyzeDialogBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreAnalyzeDialogBase(object):
    def setupUi(self, PreAnalyzeDialogBase):
        PreAnalyzeDialogBase.setObjectName("PreAnalyzeDialogBase")
        PreAnalyzeDialogBase.resize(400, 166)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreAnalyzeDialogBase)
        self.buttonBox.setGeometry(QtCore.QRect(40, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(PreAnalyzeDialogBase)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 371, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.locPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.locPushButton.setObjectName("locPushButton")
        self.horizontalLayout.addWidget(self.locPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PreAnalyzeDialogBase)
        self.buttonBox.accepted.connect(PreAnalyzeDialogBase.accept)
        self.buttonBox.rejected.connect(PreAnalyzeDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(PreAnalyzeDialogBase)

    def retranslateUi(self, PreAnalyzeDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PreAnalyzeDialogBase.setWindowTitle(_translate("PreAnalyzeDialogBase", "Analysis settings"))
        self.checkBox.setText(_translate("PreAnalyzeDialogBase", "Use Default Settings (shades of green)"))
        self.label.setText(_translate("PreAnalyzeDialogBase", "Settings file location with colors to detect:"))
        self.locPushButton.setText(_translate("PreAnalyzeDialogBase", "..."))
